### ISSUE TITLE
前后端分离和多核支持

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [MrGreyfun/Local-Code-Interpreter#17]
期望增加：
1、前后端分离特性，目前使用gradio api报错
2、每个用户一个jupter内核

**Comment by MrGreyfun** [comment]
你好，目前每次访问网页链接都会实例化一个bot后端，每个bot后端会分配一个独立的jupyter内核，互不干扰。此外，由于本项目设计之初就是为了本地运行，目前不考虑加入多用户特性。gradio api报错的详细信息能否提供？

**Comment by shanmu-raoyunfei** [comment]
> 感谢回复，验证了确实每次访问的bot是独立的。 gradio api报错的详细信息：
> 
> 客户端： Loaded as API: http://127.0.0.1:7860/ ✔ Traceback (most recent call last): File "/Users/raoyunfei/test.py", line 4, in result = client.predict( ^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/client.py", line 291, in predict return self.submit(*args, api_name=api_name, fn_index=fn_index).result() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/client.py", line 1120, in result return super().result(timeout=timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result return self.__get_result() ^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result raise self._exception File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/client.py", line 793, in _inner predictions = _predict(*data) ^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/client.py", line 824, in _predict raise ValueError(result["error"]) ValueError: None
> 
> 服务端web_UI: Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. 0.00s - Debugger warning: It seems that frozen modules are being used, which may 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off 0.00s - to python to disable frozen modules. 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation. 0.00s - Debugger warning: It seems that frozen modules are being used, which may 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off 0.00s - to python to disable frozen modules. 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation. Traceback (most recent call last): File "/opt/homebrew/lib/python3.11/site-packages/gradio/routes.py", line 442, in run_predict output = await app.get_blocks().process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/gradio/blocks.py", line 1392, in process_api result = await self.call_function( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/gradio/blocks.py", line 1097, in call_function prediction = await anyio.to_thread.run_sync( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future ^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/lib/python3.11/site-packages/gradio/utils.py", line 703, in wrapper response = f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/Users/raoyunfei/Local-Code-Interpreter/src/web_ui.py", line 21, in switch_to_gpt4 bot_backend.update_gpt_model_choice("GPT-4") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'update_gpt_model_choice'

gradio api客户端调用的代码：
from gradio_client import Client

client = Client("http://127.0.0.1:7860/")
result = client.predict(
                True,   # bool in 'Use GPT-4' Checkbox component
                fn_index=0
)
print(result)

**Comment by derek5965** [comment]
同样遇到 这个问题 gradio客户端完全不可用  多个都报错 包括python 和js客户端 最新版本都不可以，导致前端无法脱离
@MrGreyfun 能否提供一个gradio客户端 调用api成功的案例？

**Comment by MrGreyfun** [comment]
目前来看一般是版本问题，如果使用anaconda的话，可以考虑新建一个conda环境，设置python版本为3.9，然后安装README中指定的包版本
