### ISSUE TITLE
上传文件后不能返回结果

### ISSUE THREAD

**Issue by Yaolinwang** [MrGreyfun/Local-Code-Interpreter#21]
1. windows机器
2. 模型：gpt-3.5-turbo-0613
3. 文字聊天没问题
4. 上传文件之后聊天会卡主 - 没有报error（前端/后端）
![local_interpreter](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/26902034/924c7274-48ac-443b-be01-53f5b9c24c6c)

**Comment by MrGreyfun** [comment]
每次都是这样吗？感觉是网络问题

**Comment by Yaolinwang** [comment]
hello 感谢快速回复。过了许久（大概20-30分钟左右），前端返回了这个错误：Backend error: There is no current event loop in thread 'AnyIO worker thread'. 

![local_interpreter 2](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/26902034/63702bf4-caef-42f8-8156-5d82eba917e2)

**Comment by Yaolinwang** [comment]
更新：
尝试在另一台机器上使用（换成了官方api）；响应速度快很多。上传文件后可以多轮对话。但是在上传文件后要求画图的时候又出现了相同的error：
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/26902034/f99e512f-5827-410e-a11e-be19771abfbe)

**Comment by Yaolinwang** [comment]
后端的error:

To create a public link, set `share=True` in `launch()`.
C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\zmq\_future.py:679: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  self._get_loop()
Traceback (most recent call last):
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\gradio\blocks.py", line 1111, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\gradio\utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\gradio\utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\gradio\utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\site-packages\gradio\utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\xyz\Desktop\local_interp\v1\src\web_ui.py", line 112, in bot
    exit(-1)
  File "C:\Users\xyz\anaconda3\envs\openaienv\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: -1

**Comment by MrGreyfun** [comment]
要不试试把gradio更新到最新版本，这个包确实在不同平台之间不太稳定

**Comment by Yaolinwang** [comment]
请问下在什么平台上稳定些？

另外我升级之后无法上传文件了。显示了权限问题：

To create a public link, set `share=True` in `launch()`.
C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\zmq\_future.py:679: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  self._get_loop()
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xyz\.conda\envs\openaienv\lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\xyz\\AppData\\Local\\Temp\\tmpvq5rqedo' -> 'C:\\Users\\xyz\\AppData\\Local\\Temp\\gradio\\67cac232ecee98c18322886fd1855f909caa82b5\\net_mv.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\gradio\routes.py", line 706, in upload_file
    await anyio.to_thread.run_sync(
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xyz\.conda\envs\openaienv\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\xyz\.conda\envs\openaienv\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "C:\Users\xyz\.conda\envs\openaienv\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\xyz\.conda\envs\openaienv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\xyz\.conda\envs\openaienv\lib\shutil.py", line 846, in move
    os.unlink(src)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\xyz\\AppData\\Local\\Temp\\tmpvq5rqedo'
