### ISSUE TITLE
当我用设置了中转的API后 分析上传的文件报错这些  Bad Request

### ISSUE THREAD

**Issue by skyyings** [MrGreyfun/Local-Code-Interpreter#41]
```
Traceback (most recent call last):
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/gradio/blocks.py", line 1111, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/kemove/gpt/Local-Code-Interpreter/src/web_ui.py", line 127, in bot
    response = chat_completion(bot_backend=bot_backend)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/gpt/Local-Code-Interpreter/src/functional.py", line 60, in chat_completion
    response = openai.ChatCompletion.create(**kwargs_for_chat_completion)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/kemove/anaconda3/envs/lci/lib/python3.11/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: Bad Request
 (request id: 202312281451306432096718WqWWbL6) {"error":{"message":"Bad Request\n (request id: 202312281451306432096718WqWWbL6)","type":"invalid_request_error","param":"","code":2}} 402 {'error': {'message': 'Bad Request\n (request id: 202312281451306432096718WqWWbL6)', 'type': 'invalid_request_error', 'param': '', 'code': 2}} {'Date': 'Thu, 28 Dec 2023 06:51:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '134', 'Connection': 'keep-alive', 'X-Oneapi-Request-Id': '202312281451306432096718WqWWbL6', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=tJw8%2BnvebEXpAx5Mwqiuf6phrvTsAOgjt%2BL4toP22Wk8NloTZQhENCv%2FbXJ2VjeypB9hfXAxZBF5ij2zyCILMUF4nXL7hsOHvr5MQfY2n6kEQj2a2nUbWo9YD2DUYRjg"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '83c7e00beb2bb45b-HKG', 'alt-svc': 'h3=":443"; ma=86400'}
```

当我用设置了中转的API后 分析上传的文件报错这些

**Comment by MrGreyfun** [comment]
API base这些设置都正确吗，另外建议使用python3.9

**Comment by MrGreyfun** [comment]
你在其它软件里试过，这个API可以正常调用吗

**Comment by hellobinker** [comment]
试过 可以的

**Comment by MrGreyfun** [comment]
API base 加个/v1试试
